repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--config=pyproject.toml]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
        args: [--config=pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
